[package]
name = "minigotchi"
version = "1.0.2"
edition = "2024"
authors = ["Rik de Goede <rik.dgd@gmail.com>"]
description = "A very small tamagotchi for your desktop."
license = "MIT"

[dependencies]
macroquad = "0.4.14"
serde =  { version = "1.0", features = ["derive"] }
serde_json = "1.0"
